### ISSUE TITLE
Decompile Script Error

### ISSUE THREAD

**Issue by MiloCharmingMagician** [BLooperZ/nutcracker#18]
Freddi Fish 3 Case of the Stolen Conch Shell\game>nutcracker.exe sputm script decompile FREDDI3.HE0
FREDDI3.HE0
Game(basedir='', basename='FREDDI3', ext='.HE0', version=6, he_version=90, chiper_key=105)
Game(basedir='', basename='FREDDI3', ext='.HE0', version=6, he_version=90, chiper_key=105)
{1: 'helogo', 2: 'jalogo', 3: 'intro', 4: 'airport', 5: 'net-room', 6: 'town-square', 7: 'boutique', 8: 'jail', 9: 'crookbook', 10: 'rock-room', 11: 'junction', 12: 'arcade', 13: 'shooting-gallery', 14: 'funhouse', 15: 'organ-room', 16: 'closet', 17: 'tree-gate', 18: 'garden', 19: 'scenic-view', 20: 'phrasebook', 21: 'plane', 22: 'cockpit', 23: 'club-house', 24: 'surface', 25: 'waterfall', 26: 'cave', 27: 'luau', 28: 'island', 29: 'raft-room', 30: 'throne-room', 31: 'darkroom', 32: 'workshop', 33: 'maze1', 34: 'maze2', 35: 'maze3', 36: 'maze4', 37: 'maze5', 38: 'maze6', 39: 'maze7', 40: 'statue-room', 41: 'item-list-room', 42: 'goto-room', 43: 'inv-room', 44: 'puzzle-room', 45: 'icons', 46: 'saveload'}
========================== LECF_0001\LFLF_0001 helogo
========================== LECF_0001\LFLF_0002 jalogo
========================== LECF_0001\LFLF_0003 intro
Traceback (most recent call last):

  File "nutcracker\runner.py", line 11, in <module>

  File "typer\main.py", line 328, in __call__

  File "typer\main.py", line 311, in __call__

  File "click\core.py", line 1130, in __call__

  File "typer\core.py", line 778, in main

  File "typer\core.py", line 216, in _main

  File "click\core.py", line 1657, in invoke

  File "click\core.py", line 1657, in invoke

  File "click\core.py", line 1657, in invoke

  File "click\core.py", line 1404, in invoke

  File "click\core.py", line 760, in invoke

  File "typer\main.py", line 683, in wrapper

  File "nutcracker\sputm\windex\runner.py", line 93, in decompile

  File "nutcracker\sputm\windex\scu.py", line 42, in dump_script_file

  File "nutcracker\sputm\windex_v6.py", line 5339, in decompile_script

  File "nutcracker\sputm\windex_v6.py", line 2915, in o90_getSpriteInfo

  File "nutcracker\sputm\windex_v6.py", line 305, in defop

NotImplementedError: 0x25 o90_getSpriteInfo { BYTE hex=0x22 dec=34 } <deque([0, L.0])>

[6492] Failed to execute script 'runner' due to unhandled exception!

**Comment by Fantix38** [comment]
I have the same problem, with the exactly same error, except i try to decompile SpyFox Dry Cereal

**Comment by BLooperZ** [comment]
Thank you both for the reports, I have added some missing opcode implementations that should fix the decompilation for these games
