### ISSUE TITLE
Support for Extracting NPC Animated Sprites?

### ISSUE THREAD

**Issue by MiloCharmingMagician** [BLooperZ/nutcracker#19]
I extracted Freddi Fish 3 but don't see any images for any of the sprites like npcs, player, etc.

**Comment by SomeRandomHEFan** [comment]
From my experience using HEERip (https://github.com/suppertails66/heerip), animated sprites in HE games seem to generally be in the AKOS format, with exception of some extremely early releases of their first games, which instead use the COST format. The readme for this software claims that it only supports background and object images, so I'd assume it only supports the RMIM and OBIM formats. If you want to get images from HE games, HEERip will serve you better for now. (Even it doesn't support COST images, but you'd only encounter those in their first games' floppy releases or their corresponding demos.)

**Comment by BLooperZ** [comment]
Thank you, AKOS support is still WIP and have some problem with colors at the moment
if you would like to check it out (and have python installed) you can try following https://github.com/BLooperZ/nutcracker/issues/13#issuecomment-1273577350

For this time, it is better to use HEERip

**Comment by JeanxPereira** [comment]
python -m nutcracker.sputm.costume.akos "D:\GamingLibrary\The Curse of Monkey Island\COMI.LA0"
```
Traceback (most recent call last):
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\usuario\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\DownloadLibrary\nutcracker\src\nutcracker\sputm\costume\akos.py", line 214, in <module>
    for idx, ((xoff, yoff), im) in enumerate(
  File "D:\DownloadLibrary\nutcracker\src\nutcracker\sputm\costume\akos.py", line 173, in read_akos_resource
    locs, decoded = decode_frame(akhd, ci, cd, akpl)
  File "D:\DownloadLibrary\nutcracker\src\nutcracker\sputm\costume\akos.py", line 94, in decode_frame
    return (xoff, yoff), {
  File "D:\DownloadLibrary\nutcracker\src\nutcracker\sputm\costume\akos.py", line 65, in decode1
    assert d_data == data, (len(d_data), len(data))
AssertionError: (3276, 3277)

```

**Comment by BLooperZ** [comment]
Thank you for reporting, the error should now be fixed

**Comment by cgiturtle** [comment]
@BLooperZ the one thing i can say right now regarding the problems with the metadata mentioned in https://github.com/BLooperZ/nutcracker/issues/13#issuecomment-1273577350 is that what's parsed in https://github.com/BLooperZ/nutcracker/blob/develop/src/nutcracker/sputm/costume/akos.py#L91-L92 as the `locs` (locations?) of an image is *not* the image's x and y offsets in a 640x480 viewport but instead the _next_ image's width and height (data from akci block is being read twice in the akos parser). what i can't say right now is where the actual x, y offsets are stored
