### ISSUE TITLE
Error while decompiling scripts (Curse of Monkey Island)

### ISSUE THREAD

**Issue by GabiAle97** [BLooperZ/nutcracker#9]
I'm getting this error when trying to decompile scripts:

========================== LECF_0001\LFLF_0001 logo
Traceback (most recent call last):
  File "nutcracker\runner.py", line 11, in <module>
  File "typer\main.py", line 214, in __call__
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "typer\main.py", line 497, in wrapper
  File "nutcracker\sputm\windex\runner.py", line 60, in decompile
  File "nutcracker\sputm\windex\scu.py", line 36, in dump_script_file
  File "nutcracker\sputm\windex_v6.py", line 3940, in decompile_script
  File "nutcracker\sputm\windex_v6.py", line 291, in defop
NotImplementedError: 0x9c o8_cursorCommand { BYTE hex=0xdd dec=221 } <deque([])>
[13100] Failed to execute script 'runner' due to unhandled exception!

**Comment by BLooperZ** [comment]
Thank you, fixed
